# Обязательные настройки
messages_file: config/messages.txt # Файл с сообщениями
accounts_file: config/accounts.txt # Файл с токенами аккаунтов
chat_id: 1234567890 # ID чата, куда писать

send_delay: 2 # Задержка мкжду сообщениям (в секундах)

# Опциональные настройки
restart_after_end: False # Начать использовать файл с сообщениями заново, после отправки последнего сообщения

use_proxy: False # Использовать прокси?
proxy_file: config/proxy.txt # Файл с прокси для каждого аккаунта

telegram_settings: config/telegram_settings.yaml # Файл с настройками телеграма
log_tg: False # Отправлять все выведенные сообщения в телеграм?

log_send: True # Выводить сообщения отправленные ботом?
log_read: False # Выводить сообщения из чата?
ignore_own_messages: True # Игнорировать сообщения от собственных аккаунтов? (Временно не работает)

read_delay: 1 # Как часто читать сообщения из чата? (в секундах)

typing_delay_per_character: 0.1 # Как долго имитировать печать одного символа? (в секундах)